markdown: kramdown

plugins: [jekyll-paginate]

# Setup
title:            Hyde
tagline:          'A Jekyll theme'
description:      'A brazen two-column <a href="http://jekyllrb.com" target="_blank">Jekyll</a> theme that pairs a prominent sidebar with uncomplicated content. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
url:              https://aclloyd97.github.io
baseurl:          '/learnloudly'

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

paginate:         5
